name: Trading Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'  # Adjust this if using a different version

      - name: Compile and Run Java Program
        run: |
          javac -d out src/com/mac286/project/*.java
          java -classpath out com.mac286.project.Main
